version: '3.9'
services:
  timedrs:
    image: ghcr.io/yanorei32/timed-rs:v0.1.2
    hostname: timedrs
    container_name: timedrs__timedrs

    restart: unless-stopped

    ports:
      - "37:37"

    networks:
      - default

    deploy:
      resources:
        limits:
          memory: 128m

networks:
  default:
    name: timedrs__default
